package approval

import (
	"bytes"
	"crypto/ed25519"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"time"
)

// DeviceEnrollment is generated by a new approver after scanning a trusted
// one-time setup QR. The token itself travels only as broker transport data;
// its digest is bound to the new public key's signature.
type DeviceEnrollment struct {
	Version     int    `json:"version"`
	ServerID    string `json:"server_id"`
	DeviceID    string `json:"device_id"`
	PublicKey   []byte `json:"public_key"`
	TokenSHA256 []byte `json:"token_sha256"`
	Challenge   []byte `json:"challenge"`
	ValidUntil  string `json:"valid_until"`
}

type SignedDeviceEnrollment struct {
	Enrollment DeviceEnrollment `json:"enrollment"`
	Signature  []byte           `json:"signature"`
}

// DeviceEnrollmentSubmission separates the secret one-time token from signed
// enrollment bytes. A broker sees both, but can neither reuse nor alter them.
type DeviceEnrollmentSubmission struct {
	Enrollment SignedDeviceEnrollment `json:"enrollment"`
	Token      []byte                 `json:"token"`
}

type DeviceEnrollmentReceipt struct {
	Version          int    `json:"version"`
	ServerID         string `json:"server_id"`
	DeviceID         string `json:"device_id"`
	PublicKey        []byte `json:"public_key"`
	EnrollmentSHA256 string `json:"enrollment_sha256"`
	Challenge        []byte `json:"challenge"`
	Status           string `json:"status"`
}

type SignedDeviceEnrollmentReceipt struct {
	Receipt   DeviceEnrollmentReceipt `json:"receipt"`
	Signature []byte                  `json:"signature"`
}

func NewDeviceEnrollment(serverID, deviceID string, publicKey, token []byte, validUntil time.Time) (DeviceEnrollment, error) {
	enrollment := DeviceEnrollment{
		Version:     Version,
		ServerID:    serverID,
		DeviceID:    deviceID,
		PublicKey:   append([]byte(nil), publicKey...),
		TokenSHA256: tokenDigest(token),
		Challenge:   make([]byte, 32),
		ValidUntil:  validUntil.UTC().Format(time.RFC3339Nano),
	}
	if _, err := rand.Read(enrollment.Challenge); err != nil {
		return DeviceEnrollment{}, err
	}
	if err := validateDeviceEnrollment(enrollment); err != nil {
		return DeviceEnrollment{}, err
	}
	return enrollment, nil
}

func SignDeviceEnrollment(enrollment DeviceEnrollment, key ed25519.PrivateKey) (SignedDeviceEnrollment, error) {
	if err := validateDeviceEnrollment(enrollment); err != nil {
		return SignedDeviceEnrollment{}, err
	}
	if len(key) != ed25519.PrivateKeySize {
		return SignedDeviceEnrollment{}, errors.New("invalid device enrollment signing key")
	}
	if !bytes.Equal(key.Public().(ed25519.PublicKey), enrollment.PublicKey) {
		return SignedDeviceEnrollment{}, errors.New("device enrollment key mismatch")
	}
	data, err := message("device-enrollment", enrollment)
	if err != nil {
		return SignedDeviceEnrollment{}, err
	}
	return SignedDeviceEnrollment{
		Enrollment: enrollment,
		Signature:  ed25519.Sign(key, data),
	}, nil
}

func VerifyDeviceEnrollment(signed SignedDeviceEnrollment, serverID string, now time.Time) error {
	enrollment := signed.Enrollment
	if err := validateDeviceEnrollment(enrollment); err != nil {
		return err
	}
	if enrollment.ServerID != serverID {
		return errors.New("device enrollment server mismatch")
	}
	data, err := message("device-enrollment", enrollment)
	if err != nil {
		return err
	}
	if len(enrollment.PublicKey) != ed25519.PublicKeySize ||
		!ed25519.Verify(ed25519.PublicKey(enrollment.PublicKey), data, signed.Signature) {
		return errors.New("invalid device enrollment signature")
	}
	validUntil, err := time.Parse(time.RFC3339Nano, enrollment.ValidUntil)
	if err != nil {
		return errors.New("invalid device enrollment validity")
	}
	if !now.Before(validUntil) {
		return errors.New("device enrollment expired")
	}
	return nil
}

func SignDeviceEnrollmentReceipt(signed SignedDeviceEnrollment, now time.Time, key ed25519.PrivateKey) (SignedDeviceEnrollmentReceipt, error) {
	if err := VerifyDeviceEnrollment(signed, signed.Enrollment.ServerID, now); err != nil {
		return SignedDeviceEnrollmentReceipt{}, fmt.Errorf("verify enrollment before receipt: %w", err)
	}
	if len(key) != ed25519.PrivateKeySize {
		return SignedDeviceEnrollmentReceipt{}, errors.New("invalid authority signing key")
	}
	digest, err := deviceEnrollmentDigest(signed.Enrollment)
	if err != nil {
		return SignedDeviceEnrollmentReceipt{}, err
	}
	receipt := DeviceEnrollmentReceipt{
		Version:          Version,
		ServerID:         signed.Enrollment.ServerID,
		DeviceID:         signed.Enrollment.DeviceID,
		PublicKey:        append([]byte(nil), signed.Enrollment.PublicKey...),
		EnrollmentSHA256: digest,
		Challenge:        append([]byte(nil), signed.Enrollment.Challenge...),
		Status:           "ENROLLED",
	}
	data, err := message("device-enrollment-receipt", receipt)
	if err != nil {
		return SignedDeviceEnrollmentReceipt{}, err
	}
	return SignedDeviceEnrollmentReceipt{
		Receipt:   receipt,
		Signature: ed25519.Sign(key, data),
	}, nil
}

func VerifyDeviceEnrollmentReceipt(signed SignedDeviceEnrollment, signedReceipt SignedDeviceEnrollmentReceipt, authorityKey ed25519.PublicKey, now time.Time) error {
	if err := VerifyDeviceEnrollment(signed, signed.Enrollment.ServerID, now); err != nil {
		return err
	}
	digest, err := deviceEnrollmentDigest(signed.Enrollment)
	if err != nil {
		return err
	}
	receipt := signedReceipt.Receipt
	switch {
	case receipt.Version != Version:
		err = errors.New("unsupported device enrollment receipt version")
	case receipt.ServerID != signed.Enrollment.ServerID || receipt.DeviceID != signed.Enrollment.DeviceID:
		err = errors.New("device enrollment receipt identity mismatch")
	case !bytes.Equal(receipt.PublicKey, signed.Enrollment.PublicKey):
		err = errors.New("device enrollment receipt key mismatch")
	case receipt.EnrollmentSHA256 != digest:
		err = errors.New("device enrollment receipt digest mismatch")
	case !bytes.Equal(receipt.Challenge, signed.Enrollment.Challenge):
		err = errors.New("device enrollment receipt challenge mismatch")
	case receipt.Status != "ENROLLED":
		err = errors.New("device enrollment receipt status mismatch")
	}
	if err != nil {
		return err
	}
	data, err := message("device-enrollment-receipt", receipt)
	if err != nil {
		return err
	}
	if len(authorityKey) != ed25519.PublicKeySize ||
		!ed25519.Verify(authorityKey, data, signedReceipt.Signature) {
		return errors.New("invalid device enrollment receipt signature")
	}
	return nil
}

func validateDeviceEnrollment(enrollment DeviceEnrollment) error {
	switch {
	case enrollment.Version != Version:
		return errors.New("unsupported device enrollment version")
	case enrollment.ServerID == "" || enrollment.DeviceID == "":
		return errors.New("invalid device enrollment identity")
	case len(enrollment.PublicKey) != ed25519.PublicKeySize:
		return errors.New("invalid device enrollment public key")
	case len(enrollment.TokenSHA256) != sha256.Size:
		return errors.New("invalid device enrollment token digest")
	case len(enrollment.Challenge) != 32:
		return errors.New("invalid device enrollment challenge")
	}
	if _, err := time.Parse(time.RFC3339Nano, enrollment.ValidUntil); err != nil {
		return errors.New("invalid device enrollment validity")
	}
	return nil
}

func tokenDigest(token []byte) []byte {
	if len(token) == 0 {
		return nil
	}
	sum := sha256.Sum256(token)
	return sum[:]
}

func deviceEnrollmentDigest(enrollment DeviceEnrollment) (string, error) {
	if err := validateDeviceEnrollment(enrollment); err != nil {
		return "", err
	}
	data, err := message("device-enrollment", enrollment)
	if err != nil {
		return "", err
	}
	sum := sha256.Sum256(data)
	return hex.EncodeToString(sum[:]), nil
}
